platform: x64

os: Visual Studio 2015

environment:
  CYG_ROOT: "C:\\cygwin"
  CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
  nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - "%CYG_ROOT%\\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P rsync -P patch -P make -P git -P perl"

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/appveyor-vult.sh'"

after_build:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/scripts/makezip.sh'"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

artifacts:
  - path: vult-win.zip
    name: Vult

deploy:
  description: 'New version of the Vult compiler\n\nUpdate your installation with: npm install -g vult\n or dowload the binaries from: https://github.com/modlfo/vult/releases'
  provider: GitHub
  force_update: true
  auth_token:
    secure: NnZaMwUACbe83KldLGTsSXYTcad6xdi1326Wky/xP5sU3Q8HdpBXRdC4P9kMs99X
  on:
    appveyor_repo_tag: true
