platform:
  - x86

environment:
  CYG_ROOT: "C:\\cygwin"
  CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"

install:
  - appveyor DownloadFile https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/appveyor-opam.sh
  - "%CYG_ROOT%\\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P rsync -P patch -P diffutils -P make -P unzip -P git -P m4 -P perl -P mingw64-x86_64-gcc-core"

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/appveyor-opam.sh'"

after_build:
  - pwd
  - ls
  - ls _build
  - ls _build\src
  - ls %APPVEYOR_BUILD_FOLDER%
  - find . -name "*.native"
  - cp %APPVEYOR_BUILD_FOLDER%\src\vultc.native %APPVEYOR_BUILD_FOLDER%\src\vultc.exe
  - 7z a vult.zip %APPVEYOR_BUILD_FOLDER%\src\vultc.exe runtime\vultin.c runtime\vultin.h

deploy:
  description: 'Vult Compiler'
  provider: GitHub
  auth_token:
    secure: NnZaMwUACbe83KldLGTsSXYTcad6xdi1326Wky/xP5sU3Q8HdpBXRdC4P9kMs99X
  artifact: vult.zip
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
