
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef DEMO_H
#define DEMO_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "demo.tables.h"

typedef struct _tuple___real_real__ {
   float field_0;
   float field_1;
} _tuple___real_real__;

static_inline float Demo_pitchToRate_raw_c0(int index){
   return Demo_pitchToRate_c0[index];
};

static_inline float Demo_pitchToRate_raw_c1(int index){
   return Demo_pitchToRate_c1[index];
};

static_inline float Demo_pitchToRate_raw_c2(int index){
   return Demo_pitchToRate_c2[index];
};

static_inline float Demo_pitchToRate(float pitch){
   int index;
   index = int_clip(float_to_int((0.992125984252f * pitch)),0,126);
   return (float_wrap_array(Demo_pitchToRate_c0)[index] + (pitch * (float_wrap_array(Demo_pitchToRate_c1)[index] + (pitch * float_wrap_array(Demo_pitchToRate_c2)[index]))));
}

float Demo_polyblep(float phase, float inc);

int Demo_wrap_idx(int idx_raw, int size);

static_inline float Demo_lerp(float a, float b, float t){
   return (a + (t * (b + (- a))));
};

typedef struct Demo__ctx_type_7 {
   float phase;
} Demo__ctx_type_7;

typedef Demo__ctx_type_7 Demo_cs80_vibrato_type;

static_inline void Demo__ctx_type_7_init(Demo__ctx_type_7 &_output_){
   Demo__ctx_type_7 _ctx;
   _ctx.phase = 0.0f;
   _output_ = _ctx;
   return ;
}

static_inline void Demo_cs80_vibrato_init(Demo__ctx_type_7 &_output_){
   Demo__ctx_type_7_init(_output_);
   return ;
}

float Demo_cs80_vibrato(Demo__ctx_type_7 &_ctx, float rate, float depth);

typedef struct Demo__ctx_type_8 {
   float phase;
} Demo__ctx_type_8;

typedef Demo__ctx_type_8 Demo_cs80_vco_type;

static_inline void Demo__ctx_type_8_init(Demo__ctx_type_8 &_output_){
   Demo__ctx_type_8 _ctx;
   _ctx.phase = 0.0f;
   _output_ = _ctx;
   return ;
}

static_inline void Demo_cs80_vco_init(Demo__ctx_type_8 &_output_){
   Demo__ctx_type_8_init(_output_);
   return ;
}

float Demo_cs80_vco(Demo__ctx_type_8 &_ctx, float cv, float pwm_base, float pwm_mod);

typedef struct Demo__ctx_type_9 {
   float phase;
} Demo__ctx_type_9;

typedef Demo__ctx_type_9 Demo_cs80_sub_osc_type;

static_inline void Demo__ctx_type_9_init(Demo__ctx_type_9 &_output_){
   Demo__ctx_type_9 _ctx;
   _ctx.phase = 0.0f;
   _output_ = _ctx;
   return ;
}

static_inline void Demo_cs80_sub_osc_init(Demo__ctx_type_9 &_output_){
   Demo__ctx_type_9_init(_output_);
   return ;
}

float Demo_cs80_sub_osc(Demo__ctx_type_9 &_ctx, float cv);

typedef struct Demo__ctx_type_10 {
   uint8_t prev_gate;
   float env;
} Demo__ctx_type_10;

typedef Demo__ctx_type_10 Demo_cs80_pitch_eg_type;

void Demo__ctx_type_10_init(Demo__ctx_type_10 &_output_);

static_inline void Demo_cs80_pitch_eg_init(Demo__ctx_type_10 &_output_){
   Demo__ctx_type_10_init(_output_);
   return ;
}

float Demo_cs80_pitch_eg(Demo__ctx_type_10 &_ctx, uint8_t gate, float start_pitch, float time);

typedef struct Demo__ctx_type_11 {
   float ic2eq;
   float ic1eq;
} Demo__ctx_type_11;

typedef Demo__ctx_type_11 Demo_cs80_filter_type;

void Demo__ctx_type_11_init(Demo__ctx_type_11 &_output_);

static_inline void Demo_cs80_filter_init(Demo__ctx_type_11 &_output_){
   Demo__ctx_type_11_init(_output_);
   return ;
}

float Demo_cs80_filter(Demo__ctx_type_11 &_ctx, float in_sig, float cv, float res, uint8_t is_hp);

typedef struct Demo__ctx_type_12 {
   float v;
   int state;
   uint8_t prev_gate;
} Demo__ctx_type_12;

typedef Demo__ctx_type_12 Demo_adsr_type;

void Demo__ctx_type_12_init(Demo__ctx_type_12 &_output_);

static_inline void Demo_adsr_init(Demo__ctx_type_12 &_output_){
   Demo__ctx_type_12_init(_output_);
   return ;
}

float Demo_adsr(Demo__ctx_type_12 &_ctx, uint8_t gate, float a, float d, float s, float r);

typedef struct Demo__ctx_type_13 {
   float roland_chorus_ret_1;
   float roland_chorus_ret_0;
   int pos;
   float lfo;
   float b2[1024];
   float b1[1024];
} Demo__ctx_type_13;

typedef Demo__ctx_type_13 Demo_roland_chorus_type;

void Demo__ctx_type_13_init(Demo__ctx_type_13 &_output_);

static_inline void Demo_roland_chorus_init(Demo__ctx_type_13 &_output_){
   Demo__ctx_type_13_init(_output_);
   return ;
}

void Demo_roland_chorus(Demo__ctx_type_13 &_ctx, float inL, float inR, float depth);

typedef Demo__ctx_type_13 Demo_roland_chorus_ret_0_type;

static_inline void Demo_roland_chorus_ret_0_init(Demo__ctx_type_13 &_output_){
   Demo__ctx_type_13_init(_output_);
   return ;
}

static_inline float Demo_roland_chorus_ret_0(Demo__ctx_type_13 &_ctx){
   return _ctx.roland_chorus_ret_0;
};

typedef Demo__ctx_type_13 Demo_roland_chorus_ret_1_type;

static_inline void Demo_roland_chorus_ret_1_init(Demo__ctx_type_13 &_output_){
   Demo__ctx_type_13_init(_output_);
   return ;
}

static_inline float Demo_roland_chorus_ret_1(Demo__ctx_type_13 &_ctx){
   return _ctx.roland_chorus_ret_1;
};

typedef struct Demo__ctx_type_14 {
   int write_ptr;
   float phase;
   float buffer[2048];
} Demo__ctx_type_14;

typedef Demo__ctx_type_14 Demo_pitch_shifter_type;

void Demo__ctx_type_14_init(Demo__ctx_type_14 &_output_);

static_inline void Demo_pitch_shifter_init(Demo__ctx_type_14 &_output_){
   Demo__ctx_type_14_init(_output_);
   return ;
}

float Demo_pitch_shifter(Demo__ctx_type_14 &_ctx, float in_sig);

typedef struct Demo__ctx_type_15 {
   float shimmer_reverb_ret_1;
   float shimmer_reverb_ret_0;
   float s4;
   float s3;
   float s2;
   float s1;
   int p4;
   int p3;
   int p2;
   int p1;
   float lpR;
   float lpL;
   float lfo;
   float dcR;
   float dcL;
   float d4[1979];
   float d3[1619];
   float d2[1381];
   float d1[1031];
   Demo__ctx_type_14 _inst2e8;
} Demo__ctx_type_15;

typedef Demo__ctx_type_15 Demo_shimmer_reverb_type;

void Demo__ctx_type_15_init(Demo__ctx_type_15 &_output_);

static_inline void Demo_shimmer_reverb_init(Demo__ctx_type_15 &_output_){
   Demo__ctx_type_15_init(_output_);
   return ;
}

void Demo_shimmer_reverb(Demo__ctx_type_15 &_ctx, float inL, float inR, float mix, float decay, float shimmer, float lush, float damp);

typedef Demo__ctx_type_15 Demo_shimmer_reverb_ret_0_type;

static_inline void Demo_shimmer_reverb_ret_0_init(Demo__ctx_type_15 &_output_){
   Demo__ctx_type_15_init(_output_);
   return ;
}

static_inline float Demo_shimmer_reverb_ret_0(Demo__ctx_type_15 &_ctx){
   return _ctx.shimmer_reverb_ret_0;
};

typedef Demo__ctx_type_15 Demo_shimmer_reverb_ret_1_type;

static_inline void Demo_shimmer_reverb_ret_1_init(Demo__ctx_type_15 &_output_){
   Demo__ctx_type_15_init(_output_);
   return ;
}

static_inline float Demo_shimmer_reverb_ret_1(Demo__ctx_type_15 &_ctx){
   return _ctx.shimmer_reverb_ret_1;
};

typedef struct Demo__ctx_type_16 {
   Demo__ctx_type_11 _inst760;
   Demo__ctx_type_11 _inst660;
   Demo__ctx_type_9 _inst569;
   Demo__ctx_type_8 _inst44f;
   Demo__ctx_type_8 _inst34f;
   Demo__ctx_type_10 _inst247;
   Demo__ctx_type_12 _inst132;
} Demo__ctx_type_16;

typedef Demo__ctx_type_16 Demo_cs80_voice_type;

void Demo__ctx_type_16_init(Demo__ctx_type_16 &_output_);

static_inline void Demo_cs80_voice_init(Demo__ctx_type_16 &_output_){
   Demo__ctx_type_16_init(_output_);
   return ;
}

float Demo_cs80_voice(Demo__ctx_type_16 &_ctx, uint8_t gate, float note, float pb, float vib, float pwm_amt, float sub_amt, float detune, float drive, float hp_c, float lp_c, float res, float eg_a, float eg_d, float eg_s, float eg_r, float p_start, float p_time);

typedef struct Demo__ctx_type_17 {
   float lpR;
   float lpL;
   float low_shelf_ret_1;
   float low_shelf_ret_0;
} Demo__ctx_type_17;

typedef Demo__ctx_type_17 Demo_low_shelf_type;

void Demo__ctx_type_17_init(Demo__ctx_type_17 &_output_);

static_inline void Demo_low_shelf_init(Demo__ctx_type_17 &_output_){
   Demo__ctx_type_17_init(_output_);
   return ;
}

void Demo_low_shelf(Demo__ctx_type_17 &_ctx, float inL, float inR, float freq, float gain);

typedef Demo__ctx_type_17 Demo_low_shelf_ret_0_type;

static_inline void Demo_low_shelf_ret_0_init(Demo__ctx_type_17 &_output_){
   Demo__ctx_type_17_init(_output_);
   return ;
}

static_inline float Demo_low_shelf_ret_0(Demo__ctx_type_17 &_ctx){
   return _ctx.low_shelf_ret_0;
};

typedef Demo__ctx_type_17 Demo_low_shelf_ret_1_type;

static_inline void Demo_low_shelf_ret_1_init(Demo__ctx_type_17 &_output_){
   Demo__ctx_type_17_init(_output_);
   return ;
}

static_inline float Demo_low_shelf_ret_1(Demo__ctx_type_17 &_ctx){
   return _ctx.low_shelf_ret_1;
};

typedef struct Demo__ctx_type_18 {
   float vol;
   int voice_ptr;
   float vib_rate;
   float vib_depth;
   float sub_amt;
   float rev_shimmer;
   float rev_mix;
   float rev_lush;
   float rev_decay;
   float rev_damp;
   float res;
   float pwm_amt;
   float process_ret_1;
   float process_ret_0;
   float pb;
   float p_time;
   float p_start;
   float n6;
   float n5;
   float n4;
   float n3;
   float n2;
   float n1;
   float lp_c;
   float hp_c;
   uint8_t g6;
   uint8_t g5;
   uint8_t g4;
   uint8_t g3;
   uint8_t g2;
   uint8_t g1;
   float eg_s;
   float eg_r;
   float eg_d;
   float eg_a;
   float drive;
   float detune;
   float chorus_depth;
   Demo__ctx_type_15 _inst96e;
   Demo__ctx_type_13 _inst8e7;
   Demo__ctx_type_16 _inst76a;
   Demo__ctx_type_16 _inst66a;
   Demo__ctx_type_16 _inst56a;
   Demo__ctx_type_16 _inst46a;
   Demo__ctx_type_16 _inst36a;
   Demo__ctx_type_16 _inst26a;
   Demo__ctx_type_7 _inst123;
   Demo__ctx_type_17 _inst10d1;
} Demo__ctx_type_18;

typedef Demo__ctx_type_18 Demo_process_type;

void Demo__ctx_type_18_init(Demo__ctx_type_18 &_output_);

static_inline void Demo_process_init(Demo__ctx_type_18 &_output_){
   Demo__ctx_type_18_init(_output_);
   return ;
}

void Demo_process(Demo__ctx_type_18 &_ctx, float input);

typedef Demo__ctx_type_18 Demo_process_ret_0_type;

static_inline void Demo_process_ret_0_init(Demo__ctx_type_18 &_output_){
   Demo__ctx_type_18_init(_output_);
   return ;
}

static_inline float Demo_process_ret_0(Demo__ctx_type_18 &_ctx){
   return _ctx.process_ret_0;
};

typedef Demo__ctx_type_18 Demo_process_ret_1_type;

static_inline void Demo_process_ret_1_init(Demo__ctx_type_18 &_output_){
   Demo__ctx_type_18_init(_output_);
   return ;
}

static_inline float Demo_process_ret_1(Demo__ctx_type_18 &_ctx){
   return _ctx.process_ret_1;
};

typedef Demo__ctx_type_18 Demo_noteOn_type;

static_inline void Demo_noteOn_init(Demo__ctx_type_18 &_output_){
   Demo__ctx_type_18_init(_output_);
   return ;
}

void Demo_noteOn(Demo__ctx_type_18 &_ctx, int n, int v, int ch);

typedef Demo__ctx_type_18 Demo_noteOff_type;

static_inline void Demo_noteOff_init(Demo__ctx_type_18 &_output_){
   Demo__ctx_type_18_init(_output_);
   return ;
}

void Demo_noteOff(Demo__ctx_type_18 &_ctx, int n, int ch);

typedef Demo__ctx_type_18 Demo_controlChange_type;

static_inline void Demo_controlChange_init(Demo__ctx_type_18 &_output_){
   Demo__ctx_type_18_init(_output_);
   return ;
}

void Demo_controlChange(Demo__ctx_type_18 &_ctx, int c, int v, int ch);

typedef Demo__ctx_type_18 Demo_default_type;

static_inline void Demo_default_init(Demo__ctx_type_18 &_output_){
   Demo__ctx_type_18_init(_output_);
   return ;
}

void Demo_default(Demo__ctx_type_18 &_ctx);



#endif // DEMO_H
