
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "demo.h"

float Demo_polyblep(float phase, float inc){
   float t;
   t = (phase / inc);
   if(t < 1.f){
      return (-1.f + t + t + (- (t * t)));
   }
   else
   {
      if(t > (-1.f + (1.f / inc))){
         float t2;
         t2 = (t + (- (1.f / inc)));
         return (1.f + t2 + t2 + (t2 * t2));
      }
   }
   return 0.0f;
}

int Demo_wrap_idx(int idx_raw, int size){
   int out;
   out = (idx_raw % size);
   if(out < 0){
      out = (out + size);
   }
   return out;
}

float Demo_cs80_vibrato(Demo__ctx_type_7 &_ctx, float rate, float depth){
   float inc;
   inc = (2.26757369615e-05f * (0.5f + (10.f * rate)));
   _ctx.phase = (_ctx.phase + inc);
   if(_ctx.phase >= 1.f){
      _ctx.phase = (-1.f + _ctx.phase);
   }
   return (0.5f * depth * sinf((6.2831853f * _ctx.phase)));
}

float Demo_cs80_vco(Demo__ctx_type_8 &_ctx, float cv, float pwm_base, float pwm_mod){
   float inc;
   inc = Demo_pitchToRate(float_clip(cv,0.0f,127.f));
   _ctx.phase = (_ctx.phase + inc);
   if(_ctx.phase >= 1.f){
      _ctx.phase = (-1.f + _ctx.phase);
   }
   float saw;
   saw = (1.f + Demo_polyblep(_ctx.phase,inc) + (-2.f * _ctx.phase));
   float pw;
   pw = float_clip((pwm_base + pwm_mod),0.1f,0.9f);
   float p2;
   p2 = (1.f + _ctx.phase + (- pw));
   float p2_wrapped;
   if(p2 >= 1.f){
      p2_wrapped = (-1.f + p2);
   }
   else
   {
      p2_wrapped = p2;
   }
   float naive_sq;
   if(_ctx.phase < pw){
      naive_sq = 1.f;
   }
   else
   {
      naive_sq = -1.f;
   }
   float sqr;
   sqr = (naive_sq + Demo_polyblep(_ctx.phase,inc) + (- Demo_polyblep(p2_wrapped,inc)));
   return (0.5f * (saw + sqr));
}

float Demo_cs80_sub_osc(Demo__ctx_type_9 &_ctx, float cv){
   float inc;
   inc = Demo_pitchToRate(float_clip((-12.f + cv),0.0f,127.f));
   _ctx.phase = (_ctx.phase + inc);
   if(_ctx.phase >= 1.f){
      _ctx.phase = (-1.f + _ctx.phase);
   }
   float pw;
   pw = 0.5f;
   float p2;
   p2 = (1.f + _ctx.phase + (- pw));
   float p2_wrapped;
   if(p2 >= 1.f){
      p2_wrapped = (-1.f + p2);
   }
   else
   {
      p2_wrapped = p2;
   }
   float naive_sq;
   if(_ctx.phase < pw){
      naive_sq = 1.f;
   }
   else
   {
      naive_sq = -1.f;
   }
   float sqr;
   sqr = (naive_sq + Demo_polyblep(_ctx.phase,inc) + (- Demo_polyblep(p2_wrapped,inc)));
   float tri;
   if(_ctx.phase < 0.5f){
      tri = (-1.f + (4.f * _ctx.phase));
   }
   else
   {
      tri = (3.f + (-4.f * _ctx.phase));
   }
   return ((0.4f * tri) + (0.6f * sqr));
}

void Demo__ctx_type_10_init(Demo__ctx_type_10 &_output_){
   Demo__ctx_type_10 _ctx;
   _ctx.prev_gate = false;
   _ctx.env = 0.0f;
   _output_ = _ctx;
   return ;
}

float Demo_cs80_pitch_eg(Demo__ctx_type_10 &_ctx, uint8_t gate, float start_pitch, float time){
   float rate;
   rate = (1.f / (0.001f + (44100.f * time)));
   if(gate == true){
      if(_ctx.prev_gate == false){
         _ctx.env = start_pitch;
      }
      _ctx.env = (_ctx.env + (rate * (- _ctx.env)));
   }
   else
   {
      _ctx.env = 0.0f;
   }
   _ctx.prev_gate = gate;
   return _ctx.env;
}

void Demo__ctx_type_11_init(Demo__ctx_type_11 &_output_){
   Demo__ctx_type_11 _ctx;
   _ctx.ic2eq = 0.0f;
   _ctx.ic1eq = 0.0f;
   _output_ = _ctx;
   return ;
}

float Demo_cs80_filter(Demo__ctx_type_11 &_ctx, float in_sig, float cv, float res, uint8_t is_hp){
   float g;
   g = float_clip((6.28318f * Demo_pitchToRate(cv)),0.001f,0.9f);
   float k;
   k = (2.f + (-1.9f * float_clip(res,0.0f,1.f)));
   float a1;
   a1 = (1.f / (1.f + (g * (g + k))));
   float a2;
   a2 = (a1 * g);
   float a3;
   a3 = (a2 * g);
   float v3;
   v3 = (in_sig + (- _ctx.ic2eq));
   float v1;
   v1 = ((_ctx.ic1eq * a1) + (a2 * v3));
   float v2;
   v2 = (_ctx.ic2eq + (_ctx.ic1eq * a2) + (a3 * v3));
   _ctx.ic1eq = ((- _ctx.ic1eq) + (2.f * v1));
   _ctx.ic2eq = ((- _ctx.ic2eq) + (2.f * v2));
   float out;
   if(is_hp == true){
      out = (in_sig + (- v2) + (- (k * v1)));
   }
   else
   {
      out = v2;
   }
   return out;
}

void Demo__ctx_type_12_init(Demo__ctx_type_12 &_output_){
   Demo__ctx_type_12 _ctx;
   _ctx.v = 0.0f;
   _ctx.state = 0;
   _ctx.prev_gate = false;
   _output_ = _ctx;
   return ;
}

float Demo_adsr(Demo__ctx_type_12 &_ctx, uint8_t gate, float a, float d, float s, float r){
   float a_r;
   a_r = (1.f / (0.001f + (88200.f * a)));
   float d_r;
   d_r = (1.f / (0.01f + (176400.f * d)));
   float r_r;
   r_r = (1.f / (0.01f + (220500.f * r)));
   if(gate == true){
      if(_ctx.prev_gate == false){
         _ctx.state = 1;
         _ctx.v = 0.0f;
      }
      if(_ctx.state == 1){
         _ctx.v = (_ctx.v + a_r);
         if(_ctx.v >= 1.f){
            _ctx.v = 1.f;
            _ctx.state = 2;
         }
      }
      else
      {
         if(_ctx.state == 2){
            _ctx.v = (_ctx.v + (d_r * (s + (- _ctx.v))));
         }
      }
   }
   else
   {
      _ctx.state = 0;
      _ctx.v = (_ctx.v + (r_r * (- _ctx.v)));
   }
   _ctx.prev_gate = gate;
   return _ctx.v;
}

void Demo__ctx_type_13_init(Demo__ctx_type_13 &_output_){
   Demo__ctx_type_13 _ctx;
   _ctx.roland_chorus_ret_1 = 0.0f;
   _ctx.roland_chorus_ret_0 = 0.0f;
   _ctx.pos = 0;
   _ctx.lfo = 0.0f;
   ;
   ;
   _output_ = _ctx;
   return ;
}

void Demo_roland_chorus(Demo__ctx_type_13 &_ctx, float inL, float inR, float depth){
   _ctx.pos = ((1 + _ctx.pos) % 1024);
   _ctx.b1[_ctx.pos] = inL;
   _ctx.b2[_ctx.pos] = inR;
   _ctx.lfo = (1.36054421769e-05f + _ctx.lfo);
   if(_ctx.lfo >= 1.f){
      _ctx.lfo = 0.0f;
   }
   float tri;
   if(_ctx.lfo < 0.5f){
      tri = (-1.f + (4.f * _ctx.lfo));
   }
   else
   {
      tri = (3.f + (-4.f * _ctx.lfo));
   }
   float mod_depth;
   mod_depth = (150.f * depth);
   float offset1;
   offset1 = (660.f + (mod_depth * tri));
   float offset2;
   offset2 = (660.f + (- (mod_depth * tri)));
   int i1;
   i1 = float_to_int(offset1);
   float f1;
   f1 = (offset1 + (- int_to_float(i1)));
   float t1;
   t1 = Demo_lerp(_ctx.b1[Demo_wrap_idx((_ctx.pos + (- i1)),1024)],_ctx.b1[Demo_wrap_idx(((-1) + _ctx.pos + (- i1)),1024)],f1);
   int i2;
   i2 = float_to_int(offset2);
   float f2;
   f2 = (offset2 + (- int_to_float(i2)));
   float t2;
   t2 = Demo_lerp(_ctx.b2[Demo_wrap_idx((_ctx.pos + (- i2)),1024)],_ctx.b2[Demo_wrap_idx(((-1) + _ctx.pos + (- i2)),1024)],f2);
   _ctx.roland_chorus_ret_0 = ((0.5f * inL) + (0.5f * t1));
   _ctx.roland_chorus_ret_1 = ((0.5f * inR) + (0.5f * t2));
   return ;
}

void Demo__ctx_type_14_init(Demo__ctx_type_14 &_output_){
   Demo__ctx_type_14 _ctx;
   _ctx.write_ptr = 0;
   _ctx.phase = 0.0f;
   ;
   _output_ = _ctx;
   return ;
}

float Demo_pitch_shifter(Demo__ctx_type_14 &_ctx, float in_sig){
   _ctx.write_ptr = ((1 + _ctx.write_ptr) % 2048);
   _ctx.buffer[_ctx.write_ptr] = in_sig;
   _ctx.phase = (0.00048828125f + _ctx.phase);
   if(_ctx.phase >= 1.f){
      _ctx.phase = (-1.f + _ctx.phase);
   }
   float mod1;
   mod1 = (2048.f * (1.f + (- _ctx.phase)));
   float phase2;
   if((0.5f + _ctx.phase) >= 1.f){
      phase2 = (-0.5f + _ctx.phase);
   }
   else
   {
      phase2 = (0.5f + _ctx.phase);
   }
   float mod2;
   mod2 = (2048.f * (1.f + (- phase2)));
   int i1;
   i1 = float_to_int(mod1);
   float f1;
   f1 = (mod1 + (- int_to_float(i1)));
   float tap1;
   tap1 = Demo_lerp(_ctx.buffer[Demo_wrap_idx((_ctx.write_ptr + (- i1)),2048)],_ctx.buffer[Demo_wrap_idx(((-1) + _ctx.write_ptr + (- i1)),2048)],f1);
   int i2;
   i2 = float_to_int(mod2);
   float f2;
   f2 = (mod2 + (- int_to_float(i2)));
   float tap2;
   tap2 = Demo_lerp(_ctx.buffer[Demo_wrap_idx((_ctx.write_ptr + (- i2)),2048)],_ctx.buffer[Demo_wrap_idx(((-1) + _ctx.write_ptr + (- i2)),2048)],f2);
   float fade;
   if(_ctx.phase < 0.5f){
      fade = (2.f * _ctx.phase);
   }
   else
   {
      fade = (2.f + (-2.f * _ctx.phase));
   }
   return ((fade * tap1) + (tap2 * (1.f + (- fade))));
}

void Demo__ctx_type_15_init(Demo__ctx_type_15 &_output_){
   Demo__ctx_type_15 _ctx;
   _ctx.shimmer_reverb_ret_1 = 0.0f;
   _ctx.shimmer_reverb_ret_0 = 0.0f;
   _ctx.s4 = 0.0f;
   _ctx.s3 = 0.0f;
   _ctx.s2 = 0.0f;
   _ctx.s1 = 0.0f;
   _ctx.p4 = 0;
   _ctx.p3 = 0;
   _ctx.p2 = 0;
   _ctx.p1 = 0;
   _ctx.lpR = 0.0f;
   _ctx.lpL = 0.0f;
   _ctx.lfo = 0.0f;
   _ctx.dcR = 0.0f;
   _ctx.dcL = 0.0f;
   ;
   ;
   ;
   ;
   Demo__ctx_type_14_init(_ctx._inst2e8);
   _output_ = _ctx;
   return ;
}

void Demo_shimmer_reverb(Demo__ctx_type_15 &_ctx, float inL, float inR, float mix, float decay, float shimmer, float lush, float damp){
   _ctx.p1 = ((1 + _ctx.p1) % 1031);
   _ctx.p2 = ((1 + _ctx.p2) % 1381);
   _ctx.p3 = ((1 + _ctx.p3) % 1619);
   _ctx.p4 = ((1 + _ctx.p4) % 1979);
   _ctx.lfo = (3.40136054422e-06f + _ctx.lfo);
   if(_ctx.lfo >= 1.f){
      _ctx.lfo = 0.0f;
   }
   float mod;
   mod = (12.f * lush * sinf((6.2831853f * _ctx.lfo)));
   float f1;
   f1 = (0.5f * (_ctx.s1 + _ctx.s2 + _ctx.s3 + _ctx.s4));
   float f2;
   f2 = (0.5f * (_ctx.s1 + _ctx.s3 + (- _ctx.s2) + (- _ctx.s4)));
   float f3;
   f3 = (0.5f * (_ctx.s1 + _ctx.s2 + (- _ctx.s3) + (- _ctx.s4)));
   float f4;
   f4 = (0.5f * (_ctx.s1 + _ctx.s4 + (- _ctx.s2) + (- _ctx.s3)));
   float shim_in;
   shim_in = tanhf((0.25f * (f1 + f2 + f3 + f4)));
   float shim_sig;
   shim_sig = (1.2f * shimmer * Demo_pitch_shifter(_ctx._inst2e8,shim_in));
   _ctx.lpL = (_ctx.lpL + ((1.f + (-0.9f * damp)) * (shim_sig + (- _ctx.lpL))));
   _ctx.lpR = (_ctx.lpR + ((1.f + (-0.9f * damp)) * (shim_sig + (- _ctx.lpR))));
   _ctx.dcL = (_ctx.dcL + (0.001f * (f1 + (- _ctx.dcL))));
   _ctx.dcR = (_ctx.dcR + (0.001f * (f2 + (- _ctx.dcR))));
   float fb;
   fb = (0.85f * decay);
   _ctx.d1[_ctx.p1] = (inL + tanhf(((0.5f * _ctx.lpL) + (fb * (f1 + (- _ctx.dcL))))));
   _ctx.d2[_ctx.p2] = (inR + tanhf(((0.5f * _ctx.lpR) + (fb * (f2 + (- _ctx.dcR))))));
   _ctx.d3[_ctx.p3] = (inL + tanhf((fb * (f3 + (- _ctx.dcL)))));
   _ctx.d4[_ctx.p4] = (inR + tanhf((fb * (f4 + (- _ctx.dcR)))));
   int i1;
   i1 = float_to_int((10.f + mod));
   float fr1;
   fr1 = (10.f + mod + (- int_to_float(i1)));
   _ctx.s1 = Demo_lerp(_ctx.d1[Demo_wrap_idx((_ctx.p1 + (- i1)),1031)],_ctx.d1[Demo_wrap_idx(((-1) + _ctx.p1 + (- i1)),1031)],fr1);
   int i2;
   i2 = float_to_int((10.f + mod));
   float fr2;
   fr2 = (10.f + mod + (- int_to_float(i2)));
   _ctx.s2 = Demo_lerp(_ctx.d2[Demo_wrap_idx((_ctx.p2 + (- i2)),1381)],_ctx.d2[Demo_wrap_idx(((-1) + _ctx.p2 + (- i2)),1381)],fr2);
   int i3;
   i3 = float_to_int((10.f + mod));
   float fr3;
   fr3 = (10.f + mod + (- int_to_float(i3)));
   _ctx.s3 = Demo_lerp(_ctx.d3[Demo_wrap_idx((_ctx.p3 + (- i3)),1619)],_ctx.d3[Demo_wrap_idx(((-1) + _ctx.p3 + (- i3)),1619)],fr3);
   int i4;
   i4 = float_to_int((10.f + mod));
   float fr4;
   fr4 = (10.f + mod + (- int_to_float(i4)));
   _ctx.s4 = Demo_lerp(_ctx.d4[Demo_wrap_idx((_ctx.p4 + (- i4)),1979)],_ctx.d4[Demo_wrap_idx(((-1) + _ctx.p4 + (- i4)),1979)],fr4);
   float wetL;
   wetL = (0.5f * (_ctx.s1 + _ctx.s3));
   float wetR;
   wetR = (0.5f * (_ctx.s2 + _ctx.s4));
   _ctx.shimmer_reverb_ret_0 = (inL + (mix * wetL));
   _ctx.shimmer_reverb_ret_1 = (inR + (mix * wetR));
   return ;
}

void Demo__ctx_type_16_init(Demo__ctx_type_16 &_output_){
   Demo__ctx_type_16 _ctx;
   Demo__ctx_type_11_init(_ctx._inst760);
   Demo__ctx_type_11_init(_ctx._inst660);
   Demo__ctx_type_9_init(_ctx._inst569);
   Demo__ctx_type_8_init(_ctx._inst44f);
   Demo__ctx_type_8_init(_ctx._inst34f);
   Demo__ctx_type_10_init(_ctx._inst247);
   Demo__ctx_type_12_init(_ctx._inst132);
   _output_ = _ctx;
   return ;
}

float Demo_cs80_voice(Demo__ctx_type_16 &_ctx, uint8_t gate, float note, float pb, float vib, float pwm_amt, float sub_amt, float detune, float drive, float hp_c, float lp_c, float res, float eg_a, float eg_d, float eg_s, float eg_r, float p_start, float p_time){
   float amp_env;
   amp_env = Demo_adsr(_ctx._inst132,gate,eg_a,eg_d,eg_s,eg_r);
   float pit_env;
   pit_env = Demo_cs80_pitch_eg(_ctx._inst247,gate,p_start,p_time);
   float pitch;
   pitch = (note + pb + pit_env + vib);
   float osc1;
   osc1 = Demo_cs80_vco(_ctx._inst34f,pitch,0.5f,(pwm_amt * vib));
   float osc2;
   osc2 = Demo_cs80_vco(_ctx._inst44f,(pitch + (0.5f * detune)),0.5f,(pwm_amt * vib));
   float sub;
   sub = Demo_cs80_sub_osc(_ctx._inst569,pitch);
   float mixed;
   mixed = ((0.5f * (osc1 + osc2)) + (sub * sub_amt));
   float driven;
   driven = tanhf((mixed * (1.f + (4.f * drive))));
   float hpf;
   hpf = Demo_cs80_filter(_ctx._inst660,driven,hp_c,0.1f,true);
   float lpf;
   lpf = Demo_cs80_filter(_ctx._inst760,hpf,(lp_c + (70.f * amp_env)),res,false);
   return tanhf((amp_env * lpf));
}

void Demo__ctx_type_17_init(Demo__ctx_type_17 &_output_){
   Demo__ctx_type_17 _ctx;
   _ctx.lpR = 0.0f;
   _ctx.lpL = 0.0f;
   _ctx.low_shelf_ret_1 = 0.0f;
   _ctx.low_shelf_ret_0 = 0.0f;
   _output_ = _ctx;
   return ;
}

void Demo_low_shelf(Demo__ctx_type_17 &_ctx, float inL, float inR, float freq, float gain){
   float alpha;
   alpha = (6.28318f * Demo_pitchToRate(freq));
   _ctx.lpL = (_ctx.lpL + (alpha * (inL + (- _ctx.lpL))));
   _ctx.lpR = (_ctx.lpR + (alpha * (inR + (- _ctx.lpR))));
   _ctx.low_shelf_ret_0 = (inL + (_ctx.lpL * gain));
   _ctx.low_shelf_ret_1 = (inR + (_ctx.lpR * gain));
   return ;
}

void Demo__ctx_type_18_init(Demo__ctx_type_18 &_output_){
   Demo__ctx_type_18 _ctx;
   _ctx.vol = 0.0f;
   _ctx.voice_ptr = 0;
   _ctx.vib_rate = 0.0f;
   _ctx.vib_depth = 0.0f;
   _ctx.sub_amt = 0.0f;
   _ctx.rev_shimmer = 0.0f;
   _ctx.rev_mix = 0.0f;
   _ctx.rev_lush = 0.0f;
   _ctx.rev_decay = 0.0f;
   _ctx.rev_damp = 0.0f;
   _ctx.res = 0.0f;
   _ctx.pwm_amt = 0.0f;
   _ctx.process_ret_1 = 0.0f;
   _ctx.process_ret_0 = 0.0f;
   _ctx.pb = 0.0f;
   _ctx.p_time = 0.0f;
   _ctx.p_start = 0.0f;
   _ctx.n6 = 0.0f;
   _ctx.n5 = 0.0f;
   _ctx.n4 = 0.0f;
   _ctx.n3 = 0.0f;
   _ctx.n2 = 0.0f;
   _ctx.n1 = 0.0f;
   _ctx.lp_c = 0.0f;
   _ctx.hp_c = 0.0f;
   _ctx.g6 = false;
   _ctx.g5 = false;
   _ctx.g4 = false;
   _ctx.g3 = false;
   _ctx.g2 = false;
   _ctx.g1 = false;
   _ctx.eg_s = 0.0f;
   _ctx.eg_r = 0.0f;
   _ctx.eg_d = 0.0f;
   _ctx.eg_a = 0.0f;
   _ctx.drive = 0.0f;
   _ctx.detune = 0.0f;
   _ctx.chorus_depth = 0.0f;
   Demo__ctx_type_15_init(_ctx._inst96e);
   Demo__ctx_type_13_init(_ctx._inst8e7);
   Demo__ctx_type_16_init(_ctx._inst76a);
   Demo__ctx_type_16_init(_ctx._inst66a);
   Demo__ctx_type_16_init(_ctx._inst56a);
   Demo__ctx_type_16_init(_ctx._inst46a);
   Demo__ctx_type_16_init(_ctx._inst36a);
   Demo__ctx_type_16_init(_ctx._inst26a);
   Demo__ctx_type_7_init(_ctx._inst123);
   Demo__ctx_type_17_init(_ctx._inst10d1);
   _output_ = _ctx;
   return ;
}

void Demo_process(Demo__ctx_type_18 &_ctx, float input){
   float vib;
   vib = Demo_cs80_vibrato(_ctx._inst123,_ctx.vib_rate,_ctx.vib_depth);
   float o1;
   o1 = Demo_cs80_voice(_ctx._inst26a,_ctx.g1,_ctx.n1,_ctx.pb,vib,_ctx.pwm_amt,_ctx.sub_amt,_ctx.detune,_ctx.drive,_ctx.hp_c,_ctx.lp_c,_ctx.res,_ctx.eg_a,_ctx.eg_d,_ctx.eg_s,_ctx.eg_r,_ctx.p_start,_ctx.p_time);
   float o2;
   o2 = Demo_cs80_voice(_ctx._inst36a,_ctx.g2,_ctx.n2,_ctx.pb,vib,_ctx.pwm_amt,_ctx.sub_amt,_ctx.detune,_ctx.drive,_ctx.hp_c,_ctx.lp_c,_ctx.res,_ctx.eg_a,_ctx.eg_d,_ctx.eg_s,_ctx.eg_r,_ctx.p_start,_ctx.p_time);
   float o3;
   o3 = Demo_cs80_voice(_ctx._inst46a,_ctx.g3,_ctx.n3,_ctx.pb,vib,_ctx.pwm_amt,_ctx.sub_amt,_ctx.detune,_ctx.drive,_ctx.hp_c,_ctx.lp_c,_ctx.res,_ctx.eg_a,_ctx.eg_d,_ctx.eg_s,_ctx.eg_r,_ctx.p_start,_ctx.p_time);
   float o4;
   o4 = Demo_cs80_voice(_ctx._inst56a,_ctx.g4,_ctx.n4,_ctx.pb,vib,_ctx.pwm_amt,_ctx.sub_amt,_ctx.detune,_ctx.drive,_ctx.hp_c,_ctx.lp_c,_ctx.res,_ctx.eg_a,_ctx.eg_d,_ctx.eg_s,_ctx.eg_r,_ctx.p_start,_ctx.p_time);
   float o5;
   o5 = Demo_cs80_voice(_ctx._inst66a,_ctx.g5,_ctx.n5,_ctx.pb,vib,_ctx.pwm_amt,_ctx.sub_amt,_ctx.detune,_ctx.drive,_ctx.hp_c,_ctx.lp_c,_ctx.res,_ctx.eg_a,_ctx.eg_d,_ctx.eg_s,_ctx.eg_r,_ctx.p_start,_ctx.p_time);
   float o6;
   o6 = Demo_cs80_voice(_ctx._inst76a,_ctx.g6,_ctx.n6,_ctx.pb,vib,_ctx.pwm_amt,_ctx.sub_amt,_ctx.detune,_ctx.drive,_ctx.hp_c,_ctx.lp_c,_ctx.res,_ctx.eg_a,_ctx.eg_d,_ctx.eg_s,_ctx.eg_r,_ctx.p_start,_ctx.p_time);
   float mixL;
   mixL = ((0.1f * (o2 + o4 + o6)) + (0.25f * (o1 + o3 + o5)));
   float mixR;
   mixR = ((0.1f * (o1 + o3 + o5)) + (0.25f * (o2 + o4 + o6)));
   float cL;
   float cR;
   Demo_roland_chorus(_ctx._inst8e7,mixL,mixR,_ctx.chorus_depth);
   cL = Demo_roland_chorus_ret_0(_ctx._inst8e7);
   cR = Demo_roland_chorus_ret_1(_ctx._inst8e7);
   float rL;
   float rR;
   Demo_shimmer_reverb(_ctx._inst96e,cL,cR,_ctx.rev_mix,_ctx.rev_decay,_ctx.rev_shimmer,_ctx.rev_lush,_ctx.rev_damp);
   rL = Demo_shimmer_reverb_ret_0(_ctx._inst96e);
   rR = Demo_shimmer_reverb_ret_1(_ctx._inst96e);
   float outL;
   float outR;
   Demo_low_shelf(_ctx._inst10d1,rL,rR,30.f,0.5f);
   outL = Demo_low_shelf_ret_0(_ctx._inst10d1);
   outR = Demo_low_shelf_ret_1(_ctx._inst10d1);
   _ctx.process_ret_0 = (_ctx.vol * outL);
   _ctx.process_ret_1 = (_ctx.vol * outR);
   return ;
}

void Demo_noteOn(Demo__ctx_type_18 &_ctx, int n, int v, int ch){
   float rn;
   rn = int_to_float(n);
   _ctx.voice_ptr = ((1 + _ctx.voice_ptr) % 6);
   switch(_ctx.voice_ptr) {
      case 0:
         {
            _ctx.n1 = rn;
            _ctx.g1 = true;
         }
      break;
      case 1:
         {
            _ctx.n2 = rn;
            _ctx.g2 = true;
         }
      break;
      case 2:
         {
            _ctx.n3 = rn;
            _ctx.g3 = true;
         }
      break;
      case 3:
         {
            _ctx.n4 = rn;
            _ctx.g4 = true;
         }
      break;
      case 4:
         {
            _ctx.n5 = rn;
            _ctx.g5 = true;
         }
      break;
      case 5:
         {
            _ctx.n6 = rn;
            _ctx.g6 = true;
         }
      break;
    
   }
}

void Demo_noteOff(Demo__ctx_type_18 &_ctx, int n, int ch){
   float rn;
   rn = int_to_float(n);
   if(_ctx.n1 == rn){
      _ctx.g1 = false;
   }
   if(_ctx.n2 == rn){
      _ctx.g2 = false;
   }
   if(_ctx.n3 == rn){
      _ctx.g3 = false;
   }
   if(_ctx.n4 == rn){
      _ctx.g4 = false;
   }
   if(_ctx.n5 == rn){
      _ctx.g5 = false;
   }
   if(_ctx.n6 == rn){
      _ctx.g6 = false;
   }
}

void Demo_controlChange(Demo__ctx_type_18 &_ctx, int c, int v, int ch){
   float vn;
   vn = (0.00787401574803f * int_to_float(v));
   switch(c) {
      case 30:
         _ctx.vib_rate = vn;
      break;
      case 31:
         _ctx.vib_depth = vn;
      break;
      case 32:
         _ctx.pwm_amt = vn;
      break;
      case 38:
         _ctx.sub_amt = vn;
      break;
      case 39:
         _ctx.detune = vn;
      break;
      case 40:
         _ctx.drive = vn;
      break;
      case 74:
         _ctx.lp_c = (100.f * vn);
      break;
      case 71:
         _ctx.res = vn;
      break;
      case 76:
         _ctx.hp_c = (100.f * vn);
      break;
      case 73:
         _ctx.eg_a = vn;
      break;
      case 75:
         _ctx.eg_d = vn;
      break;
      case 79:
         _ctx.eg_s = vn;
      break;
      case 72:
         _ctx.eg_r = vn;
      break;
      case 80:
         _ctx.p_start = (12.f * (-0.5f + vn));
      break;
      case 81:
         _ctx.p_time = vn;
      break;
      case 82:
         _ctx.chorus_depth = vn;
      break;
      case 33:
         _ctx.rev_mix = vn;
      break;
      case 34:
         _ctx.rev_decay = vn;
      break;
      case 35:
         _ctx.rev_shimmer = vn;
      break;
      case 36:
         _ctx.rev_lush = vn;
      break;
      case 37:
         _ctx.rev_damp = vn;
      break;
      case 41:
         _ctx.vol = vn;
      break;
    
   }
}

void Demo_default(Demo__ctx_type_18 &_ctx){
   _ctx.vib_rate = 0.4f;
   _ctx.vib_depth = 0.1f;
   _ctx.pwm_amt = 0.2f;
   _ctx.sub_amt = 0.5f;
   _ctx.detune = 0.15f;
   _ctx.drive = 0.3f;
   _ctx.lp_c = 40.f;
   _ctx.hp_c = 20.f;
   _ctx.res = 0.5f;
   _ctx.eg_a = 0.01f;
   _ctx.eg_d = 0.2f;
   _ctx.eg_s = 0.4f;
   _ctx.eg_r = 0.2f;
   _ctx.p_start = 0.5f;
   _ctx.p_time = 0.05f;
   _ctx.chorus_depth = 0.7f;
   _ctx.vol = 0.8f;
   _ctx.rev_mix = 0.4f;
   _ctx.rev_decay = 0.8f;
   _ctx.rev_shimmer = 0.5f;
   _ctx.rev_lush = 0.5f;
   _ctx.rev_damp = 0.3f;
   _ctx.voice_ptr = 0;
}


