(*
   The MIT License (MIT)

   Copyright (c) 2014 Leonardo Laguna Ruiz

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
   THE SOFTWARE.
*)

(** Template for JUCE audio plugins.
    All C++ code generation is delegated to JuceData to avoid pla ppx tokenizer
    issues with ocamldep on pla 2.x. *)
open Config

let rec removeContext = function
   | IContext :: t -> removeContext t
   | x -> x
;;

let countInputs inputs = List.length (removeContext inputs)

(* Convert extracted CC params to (int * string) tuple list for juceData compatibility *)
let getCCParams (config : config) : (int * string) list =
   List.map (fun (p : cc_param) -> (p.cc_number, p.param_name)) config.cc_params
;;

let get (params : params) (header_code : Pla.t) (impl_code : Pla.t) (tables_code : Pla.t)
   : (Pla.t * FileKind.t) list
   =
   let output = params.output in
   let module_name = params.module_name in
   
   let num_inputs = countInputs params.config.process_inputs in
   let num_outputs = List.length params.config.process_outputs in

   let has_ctx = List.exists (fun a -> a = IContext) params.config.process_inputs in
   let cc_params = getCCParams params.config in

   (* Generate process call for stereo JUCE template - uses inputChannel[j] directly *)
   let inputNameStereo (i, acc) s =
      match s with
      | IContext -> i, "process_ctx" :: acc
      | _ -> i + 1, "inputChannel[j]" :: acc  (* Use direct buffer access *)
   in
   let process_args =
      List.fold_left inputNameStereo (0, []) params.config.process_inputs
      |> snd |> List.rev |> String.concat ", "
   in
   let process_call =
      module_name ^ "_process(" ^ process_args ^ ");"
   in

   (* These are kept for compatibility but not used in stereo mode *)
   let input_copies = "" in
   let output_copies = "" in

   (* Use embedded vultin runtime from juceData - no file dependency *)
   let vultin_h = JuceData.vultinHeaderStr in
   let vultin_cpp = JuceData.vultinImplStr in

   let file_upper = String.uppercase_ascii output in
   let header_pla = [%pla {|
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef <#file_upper#s>_H
#define <#file_upper#s>_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "<#output#s>.tables.h"

<#header_code#>

#endif // <#file_upper#s>_H
|}] in

   let impl_pla = [%pla {|
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "<#output#s>.h"

<#impl_code#>
|}] in

   let tables_pla = [%pla {|
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef <#file_upper#s>_TABLES_H
#define <#file_upper#s>_TABLES_H

<#tables_code#>

#endif // <#file_upper#s>_TABLES_H
|}] in

   [ Pla.string (JuceData.jucerFileStr output), FileKind.FullName (output ^ "/" ^ output ^ ".jucer")
   ; Pla.string (JuceData.processorHeaderStr output cc_params module_name has_ctx),
     FileKind.FullName (output ^ "/Source/PluginProcessor.h")
   ; Pla.string (JuceData.processorImplStr output cc_params num_inputs num_outputs
        module_name process_call input_copies output_copies "" has_ctx),
     FileKind.FullName (output ^ "/Source/PluginProcessor.cpp")
   (* GUI-less mode: no editor files needed, host provides generic parameter view *)
   ; header_pla, FileKind.FullName (output ^ "/" ^ output ^ ".h")
   ; impl_pla, FileKind.FullName (output ^ "/" ^ output ^ ".cpp")
   ; tables_pla, FileKind.FullName (output ^ "/" ^ output ^ ".tables.h")
   ; Pla.string vultin_h, FileKind.FullName (output ^ "/vultin.h")
   ; Pla.string vultin_cpp, FileKind.FullName (output ^ "/vultin.cpp")
   ; Pla.string (JuceData.jucerHeaderStr output),
     FileKind.FullName (output ^ "/JuceLibraryCode/JuceHeader.h")
   ; Pla.string (JuceData.jucerPluginDefinesStr output),
     FileKind.FullName (output ^ "/JuceLibraryCode/JucePluginDefines.h")
   ]
;;
